easy_admin:
    site_name: 'Portfolio ~ A.O'
    entities:
        # List the entity class name you want to manage
      Technologies :
          class : App\Entity\Technologies
      Projets :  
          class : App\Entity\Projets
      Experiences :  
          class : App\Entity\Experiences
       
